source 'https://rubygems.org'

gem 'rails', '~> 7.0.0'
gem 'webrick'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'rexml'
gem 'shoelace-rails', path: '../../../shoelace-rails'
gem 'webpacker', '6.0.0.rc.5'

group :development, :test do
  gem 'pry-byebug'
end

group :test do
  gem 'capybara', '>= 3.26'
  gem 'capybara-shadowdom', git: "https://github.com/yuki24/capybara-shadowdom.git"
  gem 'selenium-webdriver', '>= 4.0.0.rc3'
  gem 'webdrivers'
end
