source 'https://rubygems.org'

ruby '3.0.2'

gem 'rails', '~> 6.1.4', '>= 6.1.4.1'
gem 'puma', '~> 5.0'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'rexml'
gem 'shoelace-rails', path: '../../../shoelace-rails'
gem 'webpacker', '6.0.0.rc.5'

group :development, :test do
  gem 'pry-byebug'
end

group :test do
  gem 'capybara', '>= 3.26'
  gem 'selenium-webdriver', '>= 4.0.0.rc3'
  gem 'webdrivers'
end
